name: i2v
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.0
  - numpy
  - pip
  - python=3.8
  - pytorch
  - torchvision
  - pip:
    - gdown
    - gpustat
    - imageio
    - kornia
    - lpips
    - moviepy
    - natsort
    - omegaconf
    - opencv-python
    - pillow
    - pytorch-lightning
    - scikit-image
    - scikit-learn
    - scipy
    - tqdm
    - wandb
    - tensorflow-gan
    - tensorflow
    - tensorflow-hub
    - tensorflow-probability
    - silence-tensorflow
    - iPython
